return {
  ["builders"] = "wave15-2-unixdirdemo",
  ["id"] = "3IjZEmpxGJxreE3MWPQceK6alfE",
  ["parent"] = "3IQtgMjycyFrxa8xT2ZqwOHfdJl",
  ["pr"] = 330,
  ["repo"] = "cosmic-lua/cosmopolitan",
  ["resolution"] = "completed",
  ["title"] = "cosmopolitan: tool/net/demo/unix-dir.lua still destructures unix.localtime positionally, broken by #321",
  ["verdict"] = "accept",
  ["verdict_head"] = "9d052c17f320ba356c90deb09c73ef790175fab9",
  ["verdict_spec"] = "29b58bf6321d7e049664ee3872a2e5f3329c7ba9becc6f3fa72a826bf251badb",
}
