/*
 * The bridge: the only Lua text in the tree that is not compiled from
 * Teal, because it is what makes Teal available. It builds the handful
 * of things the vendored compiler reaches for outside the pure
 * libraries -- `io.open` and the handle it returns, `io.stderr`,
 * `io.type`, `os.getenv`, `package.path` and `package.searchers` -- over
 * the syscall table, so the compiler runs unpatched and never observes
 * that those names are gone.
 */

#ifndef COSMIC_BRIDGE_H
#define COSMIC_BRIDGE_H

static const char cosmic_bridge_source[] =
    "local root = ...\n"
    "local sys = require('cosmic.sys')\n"
    "\n"
    "local function read_all(path)\n"
    "  local fd, err = sys.open(path, sys.O_RDONLY)\n"
    "  if not fd then return nil, err end\n"
    "  local parts = {}\n"
    "  while true do\n"
    "    local chunk, rerr = sys.read(fd, 65536)\n"
    "    if not chunk then sys.close(fd); return nil, rerr end\n"
    "    if #chunk == 0 then break end\n"
    "    parts[#parts + 1] = chunk\n"
    "  end\n"
    "  sys.close(fd)\n"
    "  return table.concat(parts)\n"
    "end\n"
    "\n"
    "local function make_handle(fd)\n"
    "  local h = { is_boot_handle = true }\n"
    "  function h:read(what)\n"
    "    if what ~= '*a' and what ~= 'a' then\n"
    "      error('the boot handle reads whole files only')\n"
    "    end\n"
    "    local parts = {}\n"
    "    while true do\n"
    "      local chunk, err = sys.read(fd, 65536)\n"
    "      if not chunk then return nil, err end\n"
    "      if #chunk == 0 then break end\n"
    "      parts[#parts + 1] = chunk\n"
    "    end\n"
    "    return table.concat(parts)\n"
    "  end\n"
    "  function h:write(...)\n"
    "    local n = select('#', ...)\n"
    "    for i = 1, n do\n"
    "      local data = tostring((select(i, ...)))\n"
    "      local at = 1\n"
    "      while at <= #data do\n"
    "        local put, err = sys.write(fd, data:sub(at))\n"
    "        if not put then return nil, err end\n"
    "        at = at + put\n"
    "      end\n"
    "    end\n"
    "    return self\n"
    "  end\n"
    "  function h:flush() return self end\n"
    "  function h:close() return sys.close(fd) end\n"
    "  return h\n"
    "end\n"
    "\n"
    "local shim_io = {\n"
    "  stdout = make_handle(1),\n"
    "  stderr = make_handle(2),\n"
    "  type = function(value)\n"
    "    if type(value) == 'table' and value.is_boot_handle then\n"
    "      return 'file'\n"
    "    end\n"
    "    return nil\n"
    "  end,\n"
    "  open = function(path, mode)\n"
    "    local flags = sys.O_RDONLY\n"
    "    if mode and mode:find('w') then\n"
    "      flags = sys.O_WRONLY | sys.O_CREAT | sys.O_TRUNC\n"
    "    end\n"
    "    local fd, err = sys.open(path, flags)\n"
    "    if not fd then return nil, err end\n"
    "    return make_handle(fd)\n"
    "  end,\n"
    "}\n"
    "\n"
    "-- The pure libraries, read straight out of the global table. The\n"
    "-- hint a removed name raises is for a program someone wrote; the\n"
    "-- compiler is not one, and a name it does not find is nil, which\n"
    "-- is what plain Lua does.\n"
    "local environment = setmetatable({\n"
    "  io = shim_io,\n"
    "  os = { getenv = sys.getenv },\n"
    "  package = { path = '', searchers = {}, loaded = {} },\n"
    "}, { __index = function(_, name) return rawget(_G, name) end })\n"
    "\n"
    "local function complain(file, result)\n"
    "  local lines = {}\n"
    "  local function gather(kind, list)\n"
    "    for _, e in ipairs(list or {}) do\n"
    "      lines[#lines + 1] = string.format('%s:%d:%d: %s: %s',\n"
    "        e.filename or file, e.y or 0, e.x or 0, kind, e.msg)\n"
    "    end\n"
    "  end\n"
    "  gather('syntax error', result and result.syntax_errors)\n"
    "  gather('type error', result and result.type_errors)\n"
    "  gather('warning', result and result.warnings)\n"
    "  return table.concat(lines, '\\n')\n"
    "end\n"
    "\n"
    "local function searcher_for(tl)\n"
    "  tl.path = root .. '/?.lua;' .. root .. '/o/types/?.lua'\n"
    "  local env = assert(tl.new_env({ defaults = {\n"
    "    feat_lax = 'off', gen_compat = 'off', gen_target = '5.4',\n"
    "  } }))\n"
    "  return function(name)\n"
    "    local file = root .. '/' .. name:gsub('%.', '/') .. '.tl'\n"
    "    local source = read_all(file)\n"
    "    if not source then\n"
    "      return \"\\n\\tno file '\" .. file .. \"'\"\n"
    "    end\n"
    "    local code, result = tl.gen(source, env, nil, 'tl')\n"
    "    local trouble = complain(file, result)\n"
    "    if not code or trouble ~= '' then\n"
    "      error(file .. ': the compiler refused it\\n' .. trouble, 0)\n"
    "    end\n"
    "    local chunk, err = load(code, '@' .. name, 't')\n"
    "    if not chunk then error(file .. ': ' .. err, 0) end\n"
    "    return chunk, file\n"
    "  end\n"
    "end\n"
    "\n"
    "return { environment = environment, searcher_for = searcher_for }\n";

#endif
